exams/urls.py
from django.urls import path

from . import views

app_name = "exams"

urlpatterns = [
   path("", views.index, name="index"),
   path("save-application/<str:pk>/", views.save_application, name="save_application"),
   path("application-response/<str:pk>/", views.application_response, name="application_response"),
   path("results/", views.results, name="results"),
]

oxdu/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    i18n_patterns(
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("", include("user_sessions.urls", "user_sessions")),
        path("core/", include("core.urls", namespace="core")),
        path("accounts/", include("registration.backends.simple.urls")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("exams/", include("exams.urls", namespace="exams")),
        path("masters/", include("masters.urls", namespace="masters")),
        path("employees/", include("employees.urls", namespace="employees")),
        path("accounting/", include("accounting.urls", namespace="accounting")),
        path("branches/", include("branches.urls", namespace="branches")),
        path("courses/", include("courses.urls", namespace="courses")),
        path("admission/", include("admission.urls", namespace="admission")),
        path("tinymce/", include("tinymce.urls")),
        path("translate/", include("rosetta.urls")),
        path("i18n/", include("django.conf.urls.i18n")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
        prefix_default_language=True,
    )
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

web/urls.py
from django.conf.urls.i18n import set_language
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("courses/", views.course, name="course"),
    path("updates/", views.updates, name="updates"),
    path("events/", views.events, name="events"),
    path("careers/", views.careers, name="careers"),
    path("contact/", views.contact, name="contact"),
    path("subscription/", views.subscription, name="subscription"),
    path("branches/", views.branches, name="branches"),
    path("update/<str:slug>/", views.update_detail, name="update_detail"),
    path("course/<str:slug>/", views.course_detail, name="course_detail"),
    path("career/<str:slug>/", views.career_detail, name="career_detail"),
    path("career/success/<str:slug>/", views.career_success, name="career_success"),
    path("branch/<str:slug>/", views.branch_detail, name="branch_detail"),
    path(
        "branch/course/<str:slug>/",
        views.branch_course_detail,
        name="branch_course_detail",
    ),
    path("set_language/", set_language, name="set_language"),
    path("placements/", views.placement, name="placement"),
    path("certifications/", views.certification, name="certification"),
    path("gallery/", views.gallery, name="gallery"),
    # authenticaion
    # path("login/", views.login, name="login"),
    # path("register/", views.register, name="register"),
]

exams/models.py
from django.db import models
from django.urls import reverse


class Examination(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()
    duration = models.IntegerField()
    course = models.ForeignKey("web.Course", verbose_name="Course", on_delete=models.CASCADE)
    language = models.CharField(max_length=100, choices=(("English", "English"), ("Malayalam", "Malayalam")))
    is_active = models.BooleanField(default=True)
    total_marks = models.IntegerField(default=100)
    
    def get_list_url(self):
        return reverse("exams:index")
        
    def get_absolute_url(self):
        return reverse("exams:save_application", kwargs={"pk": self.pk})
    
    def __str__(self):
        return self.title


class Application(models.Model):
    name = models.CharField(max_length=100)
    place = models.CharField(max_length=100)
    mobile = models.CharField(max_length=100)
    email = models.EmailField()
    dob = models.DateField()
    educational_qualification = models.CharField(max_length=100)
    examination = models.ForeignKey(Examination, verbose_name="Examination", on_delete=models.CASCADE)
    mark = models.IntegerField(default=0)
    hallticket_id = models.CharField(max_length=100, blank=True, null=True)

    def message(self):
        message_txt = ""
        percentage = (self.mark / self.examination.total_marks) * 100
        if percentage >= 95:
            message_txt = "You are Eligible for 100% Scholarship."
        elif 95 > percentage >=85:
            message_txt = "You are Eligible for 30% Scholarship"
        elif 85 > percentage >=75:
            message_txt = "You are eligible for 20% Scholarship"
        elif 75 > percentage >=50:
            message_txt = "You are not Eligible for Scholarship, but you can pursue the course with full fee"
        else:
            message_txt = "You are not eligible for the Admission this time. However you can Rewrite the Examination when it is available"
        return message_txt

    def __str__(self):
        return self.name

exams/forms.py
from .models import Application
from django import forms


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ("name", "place", "mobile", "email", "dob", "educational_qualification")
        widgets = {
            "name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Your Name"}
            ),
            "place": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Your Place"}
            ),
            "mobile": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Your Mobile"}
            ),
            "email": forms.EmailInput(
                attrs={"class": "form-control", "placeholder": "Your Email"}
            ),
            "dob": forms.DateInput(
                attrs={"class": "form-control", "placeholder": "Your DOB", "type": "date"}
            ),
            "educational_qualification": forms.Select(
                attrs={"class": "form-control", "placeholder": "Your Educational Qualification"}
            ),
        }

exams/views.py
from django.shortcuts import render
from .models import Examination, Application
from .forms import ApplicationForm
from django.http import JsonResponse
from django.shortcuts import redirect


def index(request):
    examinations = Examination.objects.filter(is_active=True)
    form = ApplicationForm(request.POST or None)     
    context = {
        "examinations": examinations,
        "form": form,
    }
    return render(request, "exams/index.html", context)


def save_application(request, pk):
    examination = Examination.objects.get(pk=pk)
    form = ApplicationForm(request.POST or None)
    context = {
        "form": form,
        "exam": examination,
    }
    if request.method == "POST":
        if form.is_valid():
            application = form.save(commit=False)
            application.examination = examination
            application.save()
            redirect_url = redirect("exams:application_response", pk=application.pk)
            response_data = {
                "status": True,
                "redirect": True,
                "redirect_url": redirect_url.url,
                "title": "Success!",
                "message": "Application saved successfully",
            }
        else:
            response_data = {
                "status": False,
                "redirect": False,
                "title": "Error!",
                "message": "Invalid form",
            }
        return JsonResponse(response_data)
    return render(request, "exams/save_application.html", context)
    

def application_response(request, pk):
    application = Application.objects.get(pk=pk)
    return render(request, "exams/application_response.html", {"application": application})


def results(request):
    context = {}
    if request.GET.get("hallticket") and request.GET.get("dob"):
        hallticket_id = request.GET.get("hallticket")
        dob = request.GET.get("dob")
        application = Application.objects.filter(hallticket_id=hallticket_id, dob=dob).first()
        context["application"] = application
    return render(request, "exams/results.html", context)

templates/exams/application_response.html
{% extends 'web/base.html' %}
{% load static i18n %}


{% block content %}
<main>

   <!-- breadcrumb area start -->
   <section class="pt-20 breadcrumb__area">
      <div class="container">
         <div class="row">
            <div class="breadcrumb__list breadcrumb__list-2 mb-10">
               <span><a href="{% url 'web:index' %}">Home</a></span>
               <span class="dvdr"><i class="fa-regular fa-angle-right"></i></span>
               <span>Application Successful </span>
            </div>
         </div>
      </div>
   </section>
   <!-- breadcrumb area end -->

   <section class="contact__area pt-50 pb-120">
      <div class="container">
         <div class="row">
            <div class="col-xxl-6 col-xl-6 col-lg-6 col-md-6 mx-auto">
               <div class="course__item white-bg transition-3 mb-30 border">
                  <div class="course__content p-relative text-center">
                     <h4 class="mb-4">You have successfully registered for the Scholarship Examination. Your Application ID is <span class="text-success">{{application.hallticket_number}}</span></h4>
                     
                     <div class="d-flex flex-wrap">
                        <span class="flex_item"><i class="fa fa-calendar"></i> {{application.examination.date}}</span>
                        <span class="flex_item"><i class="fa fa-clock"></i> {{application.examination.time|date:"h:i A"}}</span>
                        <span class="flex_item"><i class="fa fa-comments"></i> {{application.examination.duration}} Minutes</span>
                        <span class="flex_item"><i class="fa fa-language"></i> {{application.examination.language}}</span>
                     </div>
                     
                     <p class="text-success mt-4">The Hallticket will be sent to your Email ID 48 Hours Before Examination</p>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </section>

</main>

{% endblock %}

templates/exams/index.html
{% extends 'web/base.html' %}
{% load static i18n %}


{% block content %}
<main>

    <!-- breadcrumb area start -->
    <section class="pt-20 breadcrumb__area">
       <div class="container">
          <div class="row">
             <div class="breadcrumb__list breadcrumb__list-2 mb-10">
                <span><a href="{% url 'web:index' %}">Home</a></span>
                <span class="dvdr"><i class="fa-regular fa-angle-right"></i></span>
                <span>Exams</span>
             </div>
          </div>
       </div>
    </section>
    <!-- breadcrumb area end -->

    <section class="course__area pb-50 pt-50">
        <div class="container">
           <div class="row">
              <div class="col-xxl-12">
                 <div class="section__title-wrapper text-center mb-60">
                    <h2 class="section__title section__title-44">{% translate 'Apply for Scholarship Exams' %}</h2>
                    <p>{% blocktrans %}Unlock your potential and pursue your dreams with our scholarship exams. Apply now and download Hallticket{% endblocktrans %}
                    </p>
                 </div>
              </div>
           </div>
           <div class="row">
              {% for exam in examinations %}
              <div class="col-xxl-4 col-xl-4 col-lg-6 col-md-6">
                  <div class="course__item white-bg transition-3 mb-30 border">
                     <div class="course__content p-relative">
                        <h3 class="course__title mt-2 mb-4">
                           <a href="{{exam.get_absolute_url}}">{{exam.title}}</a>
                        </h3>

                        <div class="d-flex flex-wrap">
                           <span class="flex_item"><i class="fa fa-calendar"></i> {{exam.date}}</span>
                           <span class="flex_item"><i class="fa fa-clock"></i> {{exam.time|date:"h:i A"}}</span>
                           <span class="flex_item"><i class="fa fa-hourglass-3"></i> {{exam.duration}} Minutes</span>
                           <span class="flex_item"><i class="fa fa-language"></i> {{exam.language}}</span>
                        </div>
                        <div class="d-flex flex-wrap">
                           <a href="{{exam.get_absolute_url}}" class="tp-btn-9 mt-20 btn-sm">Apply Now</a>
                           <a href="{% url 'exams:results' %}" class="tp-btn-9 mt-20 btn-sm">View Previous Results</a>
                        </div>
                     </div>
                  </div>
               </div>
              {% endfor %}
           </div>
        </div>
     </section>

</main>

{% endblock %}

templates/exams/results.html
{% extends 'web/base.html' %}
{% load static i18n %}


{% block content %}
<main>

   <!-- breadcrumb area start -->
   <section class="pt-20 breadcrumb__area">
      <div class="container">
         <div class="row">
            <div class="breadcrumb__list breadcrumb__list-2 mb-10">
               <span><a href="{% url 'web:index' %}">Home</a></span>
               <span class="dvdr"><i class="fa-regular fa-angle-right"></i></span>
               <span>Results </span>
            </div>
         </div>
      </div>
   </section>
   <!-- breadcrumb area end -->

   <section class="contact__area pt-50 pb-120">
      <div class="container">
               
            <div class="row">
               <div class="col-xxl-8 col-xl-8 col-lg-6 mb-4 mx-auto">
                  <div class="course__item white-bg transition-3 mb-30 border">
                     <div class="course__content p-relative">
                        <h4 class="mb-4 text-center">View Scholarship Examination Results</h4>
                        <div class="row py-4">
                           <div class="col-md-10 mx-auto">
                              <form action="" method="get">
                                 <div class="row">
                                    <div class="col-md-4">
                                       <label for="id_hallticket">Hallticket Number</label>
                                       <input id="id_hallticket" type="text" name="hallticket" class="form-control" placeholder="Enter Hallticket Number" style="height: 44px;" value="{{request.GET.hallticket}}">                           
                                    </div>
                                    <div class="col-md-4">
                                       <label for="id_dob">Date of Birth</label>
                                       <input id="id_dob" type="date" name="dob" class="form-control" placeholder="Enter Date of Birth" style="height: 44px;" value="{{request.GET.dob}}">                           
                                    </div>
                                    <div class="col-md-4">
                                       <label for="id_submit"> </label>
                                       <button type="submit" class="tp-btn-9 w-100">View Result</button>
                                    </div>
                                 </div>
                              </form>
                           </div>
                        </div>
                        
                     </div>
                  </div>
                  {% if application %}
                  <div class="transition-3 mb-30">
                     <div class="course__content p-relative">
                        <div class="row">

                           <div class="col-md-6">
                              <div class="border p-2 text-center mb-2">
                                 <small>Your Score is </small>
                                 <h3>{{application.mark}}/{{application.examination.total_marks}}</h3>
                                 <p class="text-success" style="line-height: 1.4;">{{application.message}}</p>
                              </div>

                              <div class="table-responsive">
                                 <table class="table table-bordered">
                                    <tr>
                                       <th>Hallticket</th>
                                       <td>{{application.hallticket_id}}</td>
                                    </tr>
                                    <tr>
                                       <th>Name</th>
                                       <td>{{application.name}}</td>
                                    </tr>
                                    <tr>
                                       <th>Mobile</th>
                                       <td>{{application.mobile}}</td>
                                    </tr>
                                    <tr>
                                       <th>DOB</th>
                                       <td>{{application.dob}}</td>
                                    </tr>
                                 </table>
                              </div>
                              
                           </div>

                           <div class="col-md-6">
                              <div class="table-responsive">
                                 <table class="table table-bordered">
                                    <tr>
                                       <th>Marks Secured</th>
                                       <th>Eligibility</th>
                                    </tr>
                                    <tr>
                                       <td>95 and above</td>
                                       <td>100% Scholarship</td>
                                    </tr>
                                    <tr>
                                       <td>85 - 94</td>
                                       <td>30% Scholarship</td>
                                    </tr>
                                    <tr>
                                       <td>75 - 84</td>
                                       <td>20% Scholarship</td>
                                    </tr>
                                    <tr>
                                       <td>50 - 74</td>
                                       <td>No Scholarship</td>
                                    </tr>
                                    <tr>
                                       <td>Below 50</td>
                                       <td>Not Eligible for Admission</td>
                                    </tr>
                                 </table>
                              </div>
                           </div>
                           
                        </div>
                     </div>
             
                  </div>
                  {% elif request.GET.hallticket %}
                  <div class="course__item white-bg transition-3 mb-30 border">
                     <div class="course__content p-relative text-center">
                        <p class="mb-0">No Results Found</p>
                     </div>
                  </div>
                  {% endif %}
               </div>
            </div>

         </div>
      </div>
   </section>

</main>

{% endblock %}

templates/exams/save_application.html
{% extends 'web/base.html' %}
{% load static i18n %}


{% block content %}
<main>

   <!-- breadcrumb area start -->
   <section class="pt-20 breadcrumb__area">
      <div class="container">
         <div class="row">
            <div class="breadcrumb__list breadcrumb__list-2 mb-10">
               <span><a href="{% url 'web:index' %}">Home</a></span>
               <span class="dvdr"><i class="fa-regular fa-angle-right"></i></span>
               <span>Apply </span>
            </div>
         </div>
      </div>
   </section>
   <!-- breadcrumb area end -->

   <section class="contact__area pt-50 pb-120">
      <div class="container">
         
            <div class="row">
               <div class="col-xxl-8 col-xl-8 col-lg-6 mb-4 mx-auto">
                  <div class="contact__wrapper">
                     <div class="section__title-wrapper mb-40">
                        <h4 class="section__title section__title-44">Apply for Scholarship Exams</span></h4>
                        <p>Unlock your potential and pursue your dreams with our scholarship exams. </p>
                     </div>
                     <form method="post" action="" class="ajax">
                        {% csrf_token %}
                        <div class="row">
                           <div class="col-xxl-12 col-xl-12 col-md-12">
                              <div class="contact__form-input">
                                 {{ form.name.label_tag }}
                                 {{ form.name }} </div>
                           </div>
                           <div class="col-xxl-6 col-xl-6 col-md-6">
                              <div class="contact__form-input">
                                 {{ form.place.label_tag }}
                                 {{ form.place }} </div>
                           </div>
                           <div class="col-xxl-6 col-xl-6 col-md-6">
                              <div class="contact__form-input">
                                 {{ form.mobile.label_tag }}
                                 {{ form.mobile }} </div>
                           </div>
                           <div class="col-xxl-6 col-xl-6 col-md-6">
                              <div class="contact__form-input">
                                 {{ form.email.label_tag }}
                                 {{ form.email }} </div>
                           </div>
                           <div class="col-xxl-6">
                              <div class="contact__form-input">
                                 {{ form.dob.label_tag }}
                                 {{ form.dob }} </div>
                           </div>
                           <div class="col-xxl-12">
                              <div class="contact__form-input">
                                 {{ form.educational_qualification.label_tag }}
                                 {{ form.educational_qualification }} </div>
                           </div>

                           <div class="col-xxl-12">
                              <button type="submit" class="tp-btn-9 w-50 mt-20">Submit Application</button>
                           </div>
                        </div>
                     </form>
                  </div>
               </div>
               <div class="col-xxl-4 col-lg-4 mb-4">
                  <div class="course__item white-bg transition-3 mb-30 border">
                     <div class="course__content p-relative">
                        <h3 class="course__title mt-2 mb-4">
                           <a href="{{exam.get_absolute_url}}">{{exam.title}}</a>
                        </h3>
                        <span class="d-block"><strong>Date : </strong> {{exam.date}}</span>
                        <span class="d-block"><strong>Time :</strong> {{exam.time|date:"h:i A"}}</span>
                        <span class="d-block"><strong>Duration :</strong> {{exam.duration}} Minutes</span>
                        <span class="d-block"><strong>Language :</strong> {{exam.language}}</span>
                     </div>
                  </div>
               </div>
            </div>

         </div>
      </div>
   </section>

</main>

{% endblock %}