accounts/urls.py
from . import views
from django.urls import path


app_name = "accounts"

urlpatterns = [
    path("", views.UserListView.as_view(), name="user_list"),
    path("user/<str:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("new/user/", views.UserCreateView.as_view(), name="user_create"),
    path("new/user/<pk>/", views.UserCreateView.as_view(), name="user_create"),
    path("user/<str:pk>/update/", views.UserUpdateView.as_view(), name="user_update"),
    path("user/<str:pk>/delete/", views.UserDeleteView.as_view(), name="user_delete"),
]

employees/urls.py
from . import views
from django.urls import path


app_name = "employees"

urlpatterns = [
path("department/", views.DepartmentListView.as_view(), name="department_list"),
path("department/<str:pk>/", views.DepartmentDetailView.as_view(), name="department_detail"),
path("new/department/", views.DepartmentCreateView.as_view(), name="department_create"),
path("department/<str:pk>/update/", views.DepartmentUpdateView.as_view(), name="department_update"),
path("department/<str:pk>/delete/", views.DepartmentDeleteView.as_view(), name="department_delete"),
#
path("designation/", views.DesignationListView.as_view(), name="designation_list"),
path("designation/<str:pk>/", views.DesignationDetailView.as_view(), name="designation_detail"),
path("new/designation/", views.DesignationCreateView.as_view(), name="designation_create"),
path("designation/<str:pk>/update/", views.DesignationUpdateView.as_view(), name="designation_update"),
path("designation/<str:pk>/delete/", views.DesignationDeleteView.as_view(), name="designation_delete"),
#
path("profile/", views.ProfileView.as_view(), name="profile"),
path("employees/", views.EmployeeListView.as_view(), name="employee_list"),
path("employees/add/", views.EmployeeCreateView.as_view(), name="employee_create"),
path("view/<pk>/", views.EmployeeDetailView.as_view(), name="employee_detail"),
path("employees/change/<pk>/", views.EmployeeUpdateView.as_view(), name="employee_update"),
path("employees/delete/<pk>/", views.EmployeeDeleteView.as_view(), name="employee_delete"),
]

oxdu/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    i18n_patterns(
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("", include("user_sessions.urls", "user_sessions")),
        path("core/", include("core.urls", namespace="core")),
        path("accounts/", include("registration.backends.simple.urls")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("exams/", include("exams.urls", namespace="exams")),
        path("masters/", include("masters.urls", namespace="masters")),
        path("employees/", include("employees.urls", namespace="employees")),
        path("accounting/", include("accounting.urls", namespace="accounting")),
        path("branches/", include("branches.urls", namespace="branches")),
        path("courses/", include("courses.urls", namespace="courses")),
        path("admission/", include("admission.urls", namespace="admission")),
        path("tinymce/", include("tinymce.urls")),
        path("translate/", include("rosetta.urls")),
        path("i18n/", include("django.conf.urls.i18n")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
        prefix_default_language=True,
    )
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

web/urls.py
from django.conf.urls.i18n import set_language
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("courses/", views.course, name="course"),
    path("updates/", views.updates, name="updates"),
    path("events/", views.events, name="events"),
    path("careers/", views.careers, name="careers"),
    path("contact/", views.contact, name="contact"),
    path("subscription/", views.subscription, name="subscription"),
    path("branches/", views.branches, name="branches"),
    path("update/<str:slug>/", views.update_detail, name="update_detail"),
    path("course/<str:slug>/", views.course_detail, name="course_detail"),
    path("career/<str:slug>/", views.career_detail, name="career_detail"),
    path("career/success/<str:slug>/", views.career_success, name="career_success"),
    path("branch/<str:slug>/", views.branch_detail, name="branch_detail"),
    path(
        "branch/course/<str:slug>/",
        views.branch_course_detail,
        name="branch_course_detail",
    ),
    path("set_language/", set_language, name="set_language"),
    path("placements/", views.placement, name="placement"),
    path("certifications/", views.certification, name="certification"),
    path("gallery/", views.gallery, name="gallery"),
    # authenticaion
    # path("login/", views.login, name="login"),
    # path("register/", views.register, name="register"),
]

employees/models.py
import os
import uuid

from core.base import BaseModel
from core.choices import BLOOD_CHOICES
from core.choices import EMPLOYEE_STATUS_CHOICES
from core.choices import EMPLOYMENT_TYPE_CHOICES
from core.choices import GENDER_CHOICES
from core.choices import MARITAL_CHOICES
from core.choices import RESIDENCE_CHOICES
from core.choices import RELIGION_CHOICES

from django.db import models
from django.urls import reverse_lazy
from easy_thumbnails.fields import ThumbnailerImageField


class Designation(BaseModel):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse_lazy("employees:designation_detail", kwargs={"pk": self.pk})

    @staticmethod
    def get_list_url():
        return reverse_lazy("employees:designation_list")

    @staticmethod
    def get_create_url():
        return reverse_lazy("employees:designation_create")

    def get_update_url(self):
        return reverse_lazy("employees:designation_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("employees:designation_delete", kwargs={"pk": self.pk})

    def __str__(self):
        return str(self.name)

    def employee_count(self):
        return self.employee_set.filter(is_active=True).count()


class Department(BaseModel):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True, null=True)
    department_lead = models.ForeignKey("employees.Employee", on_delete=models.PROTECT, limit_choices_to={"is_active": True}, blank=True, null=True, related_name="department_lead")

    def get_absolute_url(self):
        return reverse_lazy("employees:department_detail", kwargs={"pk": self.pk})

    @staticmethod
    def get_list_url():
        return reverse_lazy("employees:department_list")

    @staticmethod
    def get_create_url():
        return reverse_lazy("employees:department_create")

    def get_update_url(self):
        return reverse_lazy("employees:department_change", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("employees:department_delete", kwargs={"pk": self.pk})

    def __str__(self):
        return str(self.name)

    def employee_count(self):
        return self.employee_set.filter(is_active=True).count()


class Employee(BaseModel):
    branch = models.ForeignKey("branches.Branch", on_delete=models.CASCADE, null=True)
    user = models.OneToOneField("accounts.User", on_delete=models.PROTECT, limit_choices_to={"is_active": True}, related_name="employee", null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    employee_id = models.CharField(max_length=128, unique=True, null=True)
    gender = models.CharField(max_length=128, choices=GENDER_CHOICES, blank=True, null=True)
    marital_status = models.CharField(max_length=128, choices=MARITAL_CHOICES, blank=True, null=True)
    personal_email = models.EmailField(max_length=128, blank=True, null=True)
    mobile = models.CharField(max_length=128, blank=True, null=True)
    whatsapp = models.CharField(max_length=128, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    religion = models.CharField(max_length=128, choices=RELIGION_CHOICES, blank=True, null=True)
    experience = models.TextField(null=True, blank=True)
    qualifications = models.TextField(null=True, blank=True)
    photo = ThumbnailerImageField(blank=True, null=True, upload_to="employees/photos/")

    # Company Info
    official_email = models.EmailField(max_length=128, blank=True, null=True)
    department = models.ForeignKey("employees.Department", on_delete=models.PROTECT, limit_choices_to={"is_active": True}, null=True)
    designation = models.ForeignKey("employees.Designation", on_delete=models.PROTECT, limit_choices_to={"is_active": True}, null=True)

    status = models.CharField(max_length=120, choices=EMPLOYEE_STATUS_CHOICES, default='Appointed')
    resigned_date = models.DateField(null=True, blank=True)
    notice_date = models.DateField('Notice Period Last Date', null=True, blank=True)
    resigned_form = models.FileField(null=True, blank=True, upload_to="resigned-form/")
    termination_date = models.DateField(null=True, blank=True)
    termination_reason = models.CharField(max_length=100, null=True, blank=True)
    # Parent Info
    father_name = models.CharField(max_length=128, blank=True, null=True)
    father_mobile = models.CharField(max_length=128, blank=True, null=True)
    mother_name = models.CharField(max_length=128, blank=True, null=True)
    guardian_name = models.CharField(max_length=128, blank=True, null=True)
    guardian_mobile = models.CharField(max_length=128, blank=True, null=True)
    relationship_with_employee = models.CharField("Guardian Relationship With Employee", max_length=128, blank=True, null=True)

    # Dates
    date_of_joining = models.DateField(blank=True, null=True)
    date_of_confirmation = models.DateField(blank=True, null=True)

    # Job Documents
    offer_letter = models.FileField(blank=True, null=True, upload_to="employees/doc/")
    joining_letter = models.FileField(blank=True, null=True, upload_to="employees/doc/")
    agreement_letter = models.FileField(blank=True, null=True, upload_to="employees/doc/")
    experience_letter = models.FileField(blank=True, null=True, upload_to="employees/doc/")
    # Residence Info
    type_of_residence = models.CharField(max_length=128, choices=RESIDENCE_CHOICES, blank=True, null=True)
    residence_name = models.CharField(max_length=128, blank=True, null=True)
    residential_address = models.TextField(blank=True, null=True)
    residence_contact = models.CharField(max_length=128, blank=True, null=True)
    residential_zip_code = models.CharField(max_length=128, blank=True, null=True)
    permanent_address = models.TextField(blank=True, null=True)
    permanent_zip_code = models.CharField(max_length=128, blank=True, null=True)

    # Account Info

    bank_name = models.CharField(max_length=128, blank=True, null=True)
    account_name = models.CharField(max_length=128, blank=True, null=True)
    account_number = models.CharField("Bank Account Number", max_length=128, blank=True, null=True)
    ifsc_code = models.CharField("Bank IFSC Code", max_length=128, blank=True, null=True)
    bank_branch = models.CharField(max_length=128, blank=True, null=True)
    pan_number = models.CharField("PAN Card Number", max_length=128, blank=True, null=True)
    employment_type = models.CharField(max_length=128, choices=EMPLOYMENT_TYPE_CHOICES, blank=True, null=True)

    # Emergency Info
    blood_group = models.CharField(max_length=128, choices=BLOOD_CHOICES, blank=True, null=True)
    basic_salary = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    hra = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    other_allowance = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    transportation_allowance = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return str(self.user)

    def fullname(self):
        if self.last_name:
            return f"{self.first_name} {self.last_name}"
        return self.first_name

    def get_absolute_url(self):
        return reverse_lazy("employees:employee_detail", kwargs={"pk": self.pk})

    def get_image_url(self):
        if self.photo:
            return self.photo.url
        return f"https://ui-avatars.com/api/?name={self.user[:2]}&background=fdc010&color=fff&size=128"

    @staticmethod
    def get_list_url():
        return reverse_lazy("employees:employee_list")

    @staticmethod
    def get_create_url():
        return reverse_lazy("employees:employee_create")

    def get_update_url(self):
        if hasattr(self.user, 'usertype') and self.user.usertype == 'manager':
            return reverse_lazy("employees:partner_update", kwargs={'pk': self.pk})
        return reverse_lazy("employees:employee_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse_lazy("employees:employee_delete", kwargs={"pk": self.pk})

    def is_hod_staff(self):
        return Department.objects.filter(department_lead=self).exists()

    def save(self, *args, **kwargs):
        if not self.pk and self.photo:
            self.photo.name = f"{uuid.uuid4()}{os.path.splitext(self.photo.name)[1]}"
        super().save(*args, **kwargs)

employees/forms.py
from core.base import BaseForm

from .models import Department
from .models import Designation
from .models import Employee
from django import forms


class DepartmentForm(BaseForm):
    class Meta:
        model = Department
        fields = "__all__"


class DesignationForm(BaseForm):
    class Meta:
        model = Designation
        fields = "__all__"


class EmployeeForm(BaseForm):
    class Meta:
        model = Employee
        exclude = ("user", "status", "resigned_date", "notice_date", "resigned_form", "termination_date", "termination_reason")


class EmployeePhotoForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['photo']
        widgets = {'photo': forms.FileInput(attrs={'class': 'form-control d-none'})}


class EmployeePersonalDataForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = (
            "is_active",
            "first_name",
            "last_name",
            "personal_email",
            "gender",
            "marital_status",
            "mobile",
            "whatsapp",
            "date_of_birth",
            "religion",
            "blood_group",
            "experience",
            "qualifications",
            "photo",
        )

    def __init__(self, *args, **kwargs):
        super(EmployeePersonalDataForm, self).__init__(*args, **kwargs)
        self.fields['experience'].widget.attrs['rows'] = 3
        self.fields['qualifications'].widget.attrs['rows'] = 3


class EmployeeParentDataForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ("is_active", "father_name", "father_mobile", "mother_name", "guardian_name", "guardian_mobile", "relationship_with_employee")


class EmployeeAddressDataForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ("is_active", "type_of_residence", "residence_name", "residential_address", "residence_contact", "residential_zip_code", "permanent_address", "permanent_zip_code")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['residential_address'].widget.attrs['rows'] = 3
        self.fields['permanent_address'].widget.attrs['rows'] = 3


class EmployeeOfficialDataForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = (
            "is_active",
            "employee_id",
            "department",
            "designation",
            "date_of_confirmation",
            "date_of_joining",
            "official_email",
            "employment_type",
            "offer_letter",
            "joining_letter",
            "agreement_letter",
            "experience_letter",
        )


class EmployeeFinancialDataForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ("is_active", "bank_name", "account_name", "bank_branch", "account_number", "ifsc_code", "basic_salary", "hra", "transportation_allowance", "other_allowance")

templates/employees/employee_form.html
{% extends 'app/base.html' %}
{% load static i18n crispy_forms_tags %}
{% block title %}{{title}}: {{app_settings.site_title}}{% endblock %}



{% block content %}

<div class="main-content app-content">
    <div class="container-fluid">

        <!-- Page Header -->
        <div class="page-header d-flex d-block justify-content-between">
            <div class="page-leftheader">
                <div class="page-title">{{ title|title }}</div>
            </div>
            <div class="page-rightheader">
                <div class="nav nav-pills justify-content-end" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <a {% if object %} href="{{ info_type_urls.personal }}" {% endif %} class="nav-link btn btn-pill me-2 mb-1 {% if is_personal %} active {% endif %}"  >Personal Data</a>
                    <a {% if object %} href="{{ info_type_urls.parent }}" {% endif %} role="button" aria-disabled="true" class="nav-link btn btn-pill me-2 mb-1 {% if is_parent %} active {% endif %}"  >Parent</a>
                    <a {% if object %} href="{{ info_type_urls.address }}" {% endif %} class="nav-link btn btn-pill me-2 mb-1 {% if is_address %} active {% endif %}"  >Address</a>
                    <a {% if object %} href="{{ info_type_urls.official }}" {% endif %} class="nav-link btn btn-pill me-2 mb-1 {% if is_official %} active {% endif %}"  >Official</a>
                    <a {% if object %} href="{{ info_type_urls.financial }}" {% endif %} class="nav-link btn btn-pill me-2 mb-1 {% if is_financial %} active {% endif %}"  >Financial</a>
                    <a 
                    {% if object %}
                      {% if object.user %} 
                          href="{% url 'accounts:user_update' object.user.pk %}"
                      {% else %}
                          href="{% url 'accounts:user_create' object.pk %}?type=account" 
                      {% endif %} 
                    {% endif %}
                    class="nav-link btn btn-pill me-2 mb-1 {% if is_account %} active {% endif %}"  >Account</a>
              </div>
            </div>
        </div>
        <!-- Page Header Close -->

        {% include 'app/partials/messages.html' %}

        <!-- Start::row-1 -->
        <div class="row">
            <div class="col-md-12">
                <div class="card custom-card">
                    <div class="card-header d-flex justify-content-between border-bottom-0">
                        <div class="card-title">{{ sub_title|title }}</div>
                       
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <form class="form-horizontal" method="post" autocomplete="off" enctype="multipart/form-data" action="">
                                {% csrf_token %}
                                {{form|crispy}}
                                <div class="row my-2">
                                    <div class="mb-3">
                                        <div class="form-group">
                                            {% if not is_account %}
                                            <input type="submit" name="save_and_next" class="btn btn-primary me-2" value="Save and Next">
                                            {% endif %}
                                            <input type="submit" name="_save" class="btn btn-primary me-2" value="Save">
                                            <button type="button" onclick="history.back()"
                                                class="border btn btn-outline-info">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            </div>
                        </div>
                      
                        
                    </div>
                    
                </div>
            </div>
        </div>
        <!--End::row-1 -->

    </div>
</div>

{% include 'employees/partials/department_form_modal.html' %}
{% include 'employees/partials/designation_form_modal.html' %}

{% endblock content %}

{% block javascript %}

{{form.media}}
<script>
    $(document).ready(function () {
        initializeSelect2WithModal('#id_department', '#department-form-modal',"Search Department");
        initializeSelect2WithModal('#id_designation', '#designation-form-modal',"Search Designation");
        handleFormSubmit("#id_department", "#department-form-modal");      
        handleFormSubmit("#id_designation", "#designation-form-modal");      
    });
</script>
{% endblock javascript %}

templates/employees/profile.html
{% extends 'app/base.html' %}
{% load static i18n crispy_forms_tags %}
{% block title %}{{object}}: {{app_settings.site_title}}{% endblock %}

{% block content %}


<div class="main-content app-content">
  <div class="container-fluid">

    <!-- Page Header -->
    <div class="page-header d-flex d-block justify-content-between">
      <div class="page-leftheader">
        <div class="page-title">{{ title|title }}</div>
      </div>
      <div class="page-rightheader">
        <div class="btn-list">
          <a class="btn btn-light3" href="javascript:void(0);" onclick="window.print();" data-bs-placement="top"
            data-bs-toggle="tooltip" title="Print"> <i class="fe fe-printer"></i> </a>

            <a class="btn btn-light3" href="{{ object.get_update_url }}"  data-bs-placement="top"
            data-bs-toggle="tooltip" title="Edit"> <i class="fe fe-edit"></i> </a>

            <a class="btn btn-light3" href="{{ object.get_delete_url }}"  data-bs-placement="top"
            data-bs-toggle="tooltip" title="Delete"> <i class="mdi mdi-delete"></i> </a>
        </div>
      </div>
    </div>
    <!-- Page Header Close -->

    <!-- Start::row-1 -->
    <div class="row">
      <div class="col-md-12">
        {% if object %}
        <div class="card custom-card">
          <div class="card-header">
            <div class="card-title d-flex align-items-center w-100">
              <h5 class="mb-0">{{object}}</h5>
            </div>
          </div>
          <div class="card-body p-0">
            <div class="table-responsive">
              <table class="table table-hover info_table mb-0" style="width:100%;">
                <tbody>
                  {% for name, value in object.get_fields|slice:"5:" %}
                  {% if value %}
                  <tr>
                    <td> {{name}} </td>
                    <td> {{ value }} </td>
                  </tr>
                  {% endif %}
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>

        </div>
        {% else %}
        <div class="card custom-card">
          <div class="card-body">
            <p class="text-center">There is nothing here</p>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
    <!--End::row-1 -->

  </div>
</div>
{% endblock content %}