core/urls.py
from . import views
from django.urls import path


app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path('general-settings/', views.GeneralSettings.as_view(), name='general_settings'),
    path('group-settings/', views.GroupSettings.as_view(), name='group_settings'),
    path('account-settings/', views.AccountSettings.as_view(), name='account_settings'),
    # branch
    
    #  academic year
    path("academic-year/", views.AcademicYearListView.as_view(), name="academicyear_list"),
    path("academic-year/<str:pk>/", views.AcademicYearDetailView.as_view(), name="academicyear_detail"),
    path("new/academic-year/", views.AcademicYearCreateView.as_view(), name="academicyear_create"),
    path("academic-year/<str:pk>/update/", views.AcademicYearUpdateView.as_view(), name="academicyear_update"),
    path("academic-year/<str:pk>/delete/", views.AcademicYearDeleteView.as_view(), name="academicyear_delete"),
    
]

oxdu/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    i18n_patterns(
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("", include("user_sessions.urls", "user_sessions")),
        path("core/", include("core.urls", namespace="core")),
        path("accounts/", include("registration.backends.simple.urls")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("exams/", include("exams.urls", namespace="exams")),
        path("masters/", include("masters.urls", namespace="masters")),
        path("employees/", include("employees.urls", namespace="employees")),
        path("accounting/", include("accounting.urls", namespace="accounting")),
        path("branches/", include("branches.urls", namespace="branches")),
        path("courses/", include("courses.urls", namespace="courses")),
        path("admission/", include("admission.urls", namespace="admission")),
        path("tinymce/", include("tinymce.urls")),
        path("translate/", include("rosetta.urls")),
        path("i18n/", include("django.conf.urls.i18n")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
        prefix_default_language=True,
    )
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

web/urls.py
from django.conf.urls.i18n import set_language
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("courses/", views.course, name="course"),
    path("updates/", views.updates, name="updates"),
    path("events/", views.events, name="events"),
    path("careers/", views.careers, name="careers"),
    path("contact/", views.contact, name="contact"),
    path("subscription/", views.subscription, name="subscription"),
    path("branches/", views.branches, name="branches"),
    path("update/<str:slug>/", views.update_detail, name="update_detail"),
    path("course/<str:slug>/", views.course_detail, name="course_detail"),
    path("career/<str:slug>/", views.career_detail, name="career_detail"),
    path("career/success/<str:slug>/", views.career_success, name="career_success"),
    path("branch/<str:slug>/", views.branch_detail, name="branch_detail"),
    path(
        "branch/course/<str:slug>/",
        views.branch_course_detail,
        name="branch_course_detail",
    ),
    path("set_language/", set_language, name="set_language"),
    path("placements/", views.placement, name="placement"),
    path("certifications/", views.certification, name="certification"),
    path("gallery/", views.gallery, name="gallery"),
    # authenticaion
    # path("login/", views.login, name="login"),
    # path("register/", views.register, name="register"),
]

templates/app/partials/filter.html
{% load i18n crispy_forms_tags %}

<div class="offcanvas offcanvas-end" id="offcanvasFilter" aria-labelledby="offcanvasFilterLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasFilterLabel">Filter Data</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <form action="" method="get">
            <div class="modal-body">
                <div class="row">
                    {% for field in filter.form %}
                    <div class="col-12">
                        <div class="form-group">
                            {{ field.errors }}
                            {{ field|as_crispy_field }}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="modal-footer">
                <button type="reset" class="btn btn-white me-auto border">{% translate "Reset" %}</button>
                <a href="javascript:void(0);" class="btn btn-outline-white border" data-bs-dismiss="modal">
                    {% translate "Cancel" %}</a>
                <button type="submit" class="btn btn-primary">{% translate "Apply" %}</button>
            </div>
        </form>
    </div>
</div>

templates/app/partials/header.html
{% load static %}
 <!-- app-header -->
 <header class="app-header">

    <!-- Start::main-header-container -->
    <div class="main-header-container container-fluid">

        <!-- Start::header-content-left -->
        <div class="header-content-left">

            <!-- Start::header-element -->
            <div class="header-element">
                <div class="horizontal-logo">
                    <a href="{% url 'core:home' %}" class="header-logo">
                        <img src="{% static 'app/assets/images/brand-logos/desktop-logo.png' %}" alt="logo" class="desktop-logo">
                        <img src="{% static 'app/assets/images/brand-logos/toggle-logo.png' %}" alt="logo" class="toggle-logo">
                        <img src="{% static 'app/assets/images/brand-logos/desktop-dark.png' %}" alt="logo" class="desktop-dark">
                        <img src="{% static 'app/assets/images/brand-logos/toggle-dark.png' %}" alt="logo" class="toggle-dark">
                        <img src="{% static 'app/assets/images/brand-logos/desktop-white.png' %}" alt="logo" class="desktop-white">
                        <img src="{% static 'app/assets/images/brand-logos/toggle-white.png' %}" alt="logo" class="toggle-white">
                    </a>
                </div>
            </div>
            <!-- End::header-element -->

            <!-- Start::header-element -->
            <div class="header-element">
                <!-- Start::header-link -->
                <a aria-label="Hide Sidebar" class="sidemenu-toggle header-link animated-arrow hor-toggle horizontal-navtoggle" data-bs-toggle="sidebar" href="javascript:void(0);">
                    <span>
                
                    </span>
                </a>
                <!-- End::header-link -->
                <!-- Start::header-search -->
                <div class="mt-0">
                    <form class="form-inline d-none d-lg-block">
                        <div class="search-element">
                            <input type="search" class="form-control header-search" placeholder="Search…" aria-label="Search" tabindex="1">
                            <button class="btn" >
                                <i class="fe fe-search"></i>
                            </button>
                        </div>
                    </form>
                </div>
                <!-- End::header-search -->
            </div>
            <!-- End::header-element -->

        </div>
        <!-- End::header-content-left -->

        <!-- Start::header-content-right -->
        <div class="header-content-right">

            <!-- Start::header-element -->
                <div class="header-element header-search d-lg-none">
                    <!-- Start::header-link -->
                    <a href="javascript:void(0);" class="header-link dropdown-toggle" data-bs-auto-close="outside" data-bs-toggle="dropdown">
                        <svg xmlns="http://www.w3.org/2000/svg" class="header-link-icon" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/></svg>
                    </a>
    
                    <ul class="main-header-dropdown dropdown-menu dropdown-menu-end" data-popper-placement="none">
                        <li>
                            <span class="dropdown-item d-flex align-items-center" >
                                <span class="input-group">
                                    <input type="text" class="form-control" placeholder="Search..." aria-label="Search input" aria-describedby="button-addon2">
                                    <button class="btn btn-primary" type="button" id="button-addon2">Search</button>
                                </span>
                            </span>
                        </li>
                    </ul>
    
                    <!-- End::header-link -->
                </div>
            <!-- End::header-element -->
            
            <div class="header-element header-details d-none d-lg-flex">
                <span class="badge bg-primary">{{ loged_academic_year }}</span>
            </div>

            <div class="header-element header-details d-none d-lg-flex">
                <span class="badge  bg-success">{{ loged_branch }}</span>
            </div>

            <!-- Start::header-element -->
            <div class="header-element header-theme-mode">
                <!-- Start::header-link|layout-setting -->
                <a href="javascript:void(0);" class="header-link layout-setting">
                    <span class="light-layout lh-1">
                        <!-- Start::header-link-icon -->
                    <i class="fe fe-moon header-link-icon"></i>
                        <!-- End::header-link-icon -->
                    </span>
                    <span class="dark-layout lh-1">
                        <!-- Start::header-link-icon -->
                    <i class="fe fe-sun header-link-icon"></i>
                        <!-- End::header-link-icon -->
                    </span>
                </a>
                <!-- End::header-link|layout-setting -->
            </div>
            <!-- End::header-element -->

            <!-- Start::header-element -->
            <div class="header-element header-fullscreen">
                <!-- Start::header-link -->
                <a onclick="openFullscreen();" href="javascript:void(0);" class="header-link">
                    <i class="fe fe-maximize full-screen-open header-link-icon"></i>
                    <i class="fe fe-minimize full-screen-close header-link-icon d-none"></i>
                </a>
                <!-- End::header-link -->
            </div>
            <!-- End::header-element -->

           

            <!-- Start::header-element -->
            <div class="header-element main-header-profile">
                <!-- Start::header-link|dropdown-toggle -->
                <a href="javascript:void(0);" class="header-link dropdown-toggle mx-0 w-100" id="mainHeaderProfile" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                    <div>
                        <img src="{% static 'app/assets/images/users/16.jpg' %}" alt="img" class="rounded-3 avatar avatar-md">
                    </div>
                </a>
                <!-- End::header-link|dropdown-toggle -->
                <ul class="main-header-dropdown dropdown-menu pt-0 header-profile-dropdown dropdown-menu-end" aria-labelledby="mainHeaderProfile">
                    <Li>
                        <div class="p-3 text-center border-bottom">
                            <a href="#" class="text-center fw-semibold">{{request.user}}</a>
                            <p class="text-center user-semi-title fs-13 mb-0">{{request.user.designation}}</p>
                        </div>
                    </Li>
                    {% comment %}
                    <li><a class="dropdown-item d-flex align-items-center" href="#"><i class="fe fe-user me-2"></i>Profile</a></li>
                    {% endcomment %}
                    <li><a class="dropdown-item d-flex align-items-center" href="{% url 'core:general_settings' %}"><i class="fe fe-settings me-2"></i>Settings</a></li>
                    <li><a class="dropdown-item d-flex align-items-center" href="{% url 'auth_password_change' %}"><i class="fe fe-edit-3 me-2"></i>Change Password</a></li>
                    <li><a class="dropdown-item d-flex align-items-center" href="{% url 'user_sessions:session_list' %}"><i class="fe fe-headphones me-2"></i>My Sessions</a></li>
                    <li><a class="dropdown-item d-flex align-items-center" href="{% url 'auth_logout' %}"><i class="fe fe-power me-2"></i>Log Out</a></li>
                </ul>
            </div>  

          

        </div>
        <!-- End::header-content-right -->

    </div>
    <!-- End::main-header-container -->

</header>
<!-- /app-header -->

templates/app/partials/messages.html
{% if messages %}
    {% for message in messages|slice:":1" %}
        {% if message.tags == "success" %}
            <div class="alert alert-outline-success alert-dismissible fade show">
        {% elif message.tags == "warning" %}
            <div class="alert alert-outline-warning alert-dismissible fade show">
        {% elif message.tags == "error" %}
            <div class="alert alert-outline-danger alert-dismissible fade show">
        {% elif message.tags == "info" %}
            <div class="alert alert-outline-info alert-dismissible fade show">
        {% else %}
            <div class="alert alert-outline-secondary alert-dismissible fade show">
        {% endif %}
            {{ message|safe }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                <i class="bi bi-x"></i>
            </button>
        </div>
    {% endfor %}
{% endif %}

templates/app/partials/table_actions.html
<a href="{{ record.get_absolute_url }}" class="btn btn-sm btn-light btn-outline-info">OPEN</a>

templates/app/partials/table_actions2.html
<a href="{{ record.get_update_url }}" class="btn btn-sm btn-light btn-outline-info">OPEN</a>